// src/components/OptimizedImage.tsx
import Image, { ImageProps } from "next/image";
import React from "react";

type OptimizedImageProps = Omit<ImageProps, "src" | "placeholder" | "blurDataURL"> & {
  src: string;
  alt: string;
  // optional low‑quality placeholder generation function
  generateBlur?: (src: string) => string;
};

/**
 * OptimizedImage wraps Next.js <Image> and automatically adds a blur placeholder
 * using a low‑quality version of the same remote image.
 *
 * It works for remote images defined in next.config.ts remotePatterns.
 * The placeholder is generated by appending a `q=10` query param (very low quality)
 * which Unsplash and many other CDNs honour.
 */
export const OptimizedImage: React.FC<OptimizedImageProps> = ({
  src,
  alt,
  generateBlur,
  ...rest
}) => {
  const blurUrl = generateBlur
    ? generateBlur(src)
    : src.includes("?")
    ? `${src}&q=10`
    : `${src}?q=10`;

  return (
    <Image
      src={src}
      alt={alt}
      placeholder="blur"
      blurDataURL={blurUrl}
      {...rest}
    />
  );
};
